version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: bissy_development
      POSTGRES_USER: bissy
      POSTGRES_PASSWORD: bissy
      PGDATA: /var/postgres_data
    volumes:
      - .data/postgres:/var/postgres_data
    ports:
      - 5432:5432

  redis:
    image: redis:6
    ports:
      - 6379:6379

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://bissy:bissy@postgres:5432/bissy_development?sslmode=disable
      - PORT=1123
    ports:
      - 1123:1123
    volumes:
      - .:/go/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    entrypoint: "./scripts/start.sh"

  postgres_test:
    image: postgres:12
    environment:
      POSTGRES_DB: bissy_test
      POSTGRES_USER: bissy
      POSTGRES_PASSWORD: bissy

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_test
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://bissy:bissy@postgres_test:5432/bissy_test?sslmode=disable
    volumes:
      - .:/go/src/app
    entrypoint: "./scripts/test.sh"
