version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: bissy_development
      POSTGRES_USER: bissy
      POSTGRES_PASSWORD: bissy
    ports:
      - 5432:5432

  redis:
    image: redis:6
    ports:
      - 6379:6379

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - REDISCLOUD_URL=redis://redis:6379
      - DATABASE_URL=postgres://bissy:bissy@postgres:5432/bissy_development?sslmode=disable
      - JWT_SIGNING_KEY=8bb1f10acd560f472b9eaaeb3ffd092d
      - PORT=1123
      - FRONTEND_ORIGIN=http://localhost:8000
      - PAGERDUTY_WEBHOOK_TOKEN=dev-token
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - SLACKERDUTY_SLACK_CHANNEL
      - SLACK_BOT_TOKEN
    ports:
      - 1123:1123
    volumes:
      - .:/go/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    entrypoint: "./scripts/start.sh"

  postgres_test:
    image: postgres:12
    environment:
      POSTGRES_DB: bissy_test
      POSTGRES_USER: bissy
      POSTGRES_PASSWORD: bissy
    ports:
      - 5433:5432

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_test
      - redis
    environment:
      - REDISCLOUD_URL=redis://redis:6379
      - DATABASE_URL=postgres://bissy:bissy@postgres_test:5432/bissy_test?sslmode=disable
    volumes:
      - .:/go/src/app
    entrypoint: "./scripts/test.sh"
