desc: "Reload tests on file change"
triggers:
- name: ""
  pattens:
  - '**/*.go'
  cmd: |
    clear
    echo ""
    echo "* Drop"
    psql -c "DROP DATABASE IF EXISTS bissy_test;" postgres://bissy:bissy@postgres_test:5432/postgres?sslmode=disable
    echo " * Create"
    psql -c "CREATE DATABASE bissy_test;" postgres://bissy:bissy@postgres_test:5432/postgres?sslmode=disable
    echo " * Deps"
    go get
    echo " * Migrate"
    migrate -path migrations -database $DATABASE_URL -verbose up
    echo " * Test"
    go test -timeout=10s -coverprofile=cover.out -parallel=4 ./...
    echo " * Coverage"
    go tool cover -html=cover.out -o coverage.html
    echo " * Lint"
    golint ./...
    echo " * DONE"
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- /go/src/app
watch_depth: 3
