desc: "Reload tests on file change"
triggers:
- name: ""
  pattens:
  - '**/*.go'
  cmd: clear; go test -v -timeout=10s -parallel=4 ./...; echo "\n* DONE\n"
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- /go/src/app
watch_depth: 3
