desc: "Reload tests on file change"
triggers:
- name: ""
  pattens:
  - '**/*.go'
  cmd: |
    clear
    go test -timeout=10s -coverprofile=cover.out -parallel=4 ./...
    go tool cover -html=cover.out -o coverage.html
    golint ./...
    echo " * DONE"
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- /go/src/app
watch_depth: 3
