# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/redis:6
      - image: circleci/postgres:11
        environment:
          POSTGRES_PASSWORD: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci

    working_directory: /go/src/github.com/CGA1123/bissy-api
    environment:
      DATABASE_URL: postgres://circleci:circleci@localhost:5432/circleci?sslmode=disable
      MIGRATE_VERSION: v4.11.0
    steps:
      - checkout
      - run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/$MIGRATE_VERSION/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /bin/migrate
          mkdir /tmp/artifacts
          migrate -database $DATABASE_URL -path migrations up
          go get -v -t -d ./...
          go test -v -parallel=4 -count=1 -timeout=10s -coverprofile=c.out ./...
          go tool cover -html=c.out -o coverage.html
          mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts




