# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          DATABASE_URL=postgres://circleci:circleci@localhost:5432/circleci
      - image: circleci/redis:6
      - image: circleci/postgres:11
        environment:
          POSTGRES_PASSWORD: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci

    working_directory: /go/src/github.com/CGA1123/bissy-api
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./... -parallel 4
      - run: go vet ./...
